spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tH5hSX7Xeoa6dof6Es4
      secret-key: RLjCLLowWXCfnucFE4mzskcWxtrVyY
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-xiozy
      sms:
        ## 以下是教程的旧版本
        ## host: https://fesms.market.alicloudapi.com
        ## path: /sms/
        ## skin: 1
        ## sign: 175622
        ## appcode: b0563c23aff8428c97a54d4f7f9e28e5
        signName: 阿里云短信测试
        templateCode: SMS_154950909
        accessKeyID: LTAI5tCa8X68wHEEXA4basQS
        accessKeySecret: eTNHuCKil71Jv0O8XixXWlHj5Kho2A


  application:
    name: gulimall-third-party

server:
  port: 30000